# Site settings
title: Visual Studio Geeks
url: "https://www.visualstudiogeeks.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Europe/London
description: "Geeky ramblings on DevOps, Visual Studio Team Services (VSTS), Azure, ALM, TFS and Visual Studio"

# Your information
#see _data\authors.yml
excerpt_separator: <!--more-->
google_analytics: UA-57919718-1
production: true

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: visualstudiogeeks   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /:categories/:title
markdown: kramdown
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-redirect-from
 - jekyll-feed

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

feed:
  path: atom.xml